url: "https://tedserbinski.com"

permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.markdown
  - s3_website.yml
  - .jekyll-metadata
  - .jekyll-cache
  - .asset-cache
  - .sass-cache
  - .git

# configuration options https://github.com/envygeeks/jekyll-assets
assets:
  cdn:
    url: https://tedserbinski.com/assets
  sources:
    - _assets
    - _assets/js
    - _assets/css
    - _assets/img/headshots
    - _assets/img/posts
    - _assets/img/posts/book-reviews
    - _assets/img/pages
