source 'https://rubygems.org'

gem 'jekyll', '~>1.0.0.rc1'
gem 'jekyll-assets'
gem 'rake'
gem 'redcarpet'
gem 'pygments.rb'
gem 'uglifier'
gem 'yui-compressor'
gem 'gsl'
gem 'jekyll-s3'
gem 'image_optim'
